import type { Contact } from '../../src/contact/contactSchema.js';

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'recLauraRees',
    name: 'Laura Rees',
    phoneNumber: '07700 900142',
    contactType: 'Member (paying)',
    tags: ['Hackney', 'Disputes'],
    phoneCallAvailability: ['Weekday evenings', 'Saturday afternoon'],
    newMemberCallDone: true,
    hadInitialOneToOne: true,
    invitedToWhatsApp: true,
    membershipNumber: 4821,
    notes:
      'Joined after the Evelyn estate dispute. Comfortable on calls — could be approached about a local organising rep role.',
    summary:
      'Last call 12/4/26: discussed the upcoming Hackney members meeting, expressed interest in attending. Confirmed phone number.',
    dateEnteredInDatabase: '2024-09-12',
  },
  {
    id: 'recJuniorCampbell',
    name: 'Junior Campbell',
    phoneNumber: '07700 900233',
    contactType: 'Interested (did not complete)',
    tags: ['Walthamstow'],
    phoneCallAvailability: ['Weekend mornings'],
    newMemberCallDone: false,
    hadInitialOneToOne: false,
    invitedToWhatsApp: false,
    notes:
      'Filled out the Get Involved form but never completed the join. Worth a friendly first call.',
    dateEnteredInDatabase: '2026-04-30',
  },
  {
    id: 'recNiamhCahill',
    name: 'Niamh Cahill',
    phoneNumber: '07700 900418',
    contactType: 'Contact',
    tags: ['Tower Hamlets', 'Mould issue'],
    phoneCallAvailability: ['Weekday evenings'],
    newMemberCallDone: false,
    hadInitialOneToOne: false,
    invitedToWhatsApp: false,
    notes:
      'Original enquiry was about mould in her flat. Referred to the mould working group but never followed up.',
    summary: 'Initial enquiry 8/2/25, no contact since.',
    dateEnteredInDatabase: '2025-02-08',
  },
  {
    id: 'recEloiseMcLean',
    name: 'Eloise McLean',
    phoneNumber: '07700 900527',
    contactType: 'Contact',
    tags: ['South London'],
    phoneCallAvailability: ['Weekday lunchtime', 'Weekend afternoons'],
    newMemberCallDone: false,
    hadInitialOneToOne: false,
    invitedToWhatsApp: false,
    dateEnteredInDatabase: '2026-05-10',
  },
  {
    id: 'recSophieBishop',
    name: 'Sophie Bishop',
    phoneNumber: '07700 900631',
    contactType: 'Interested (did not complete)',
    tags: ['Lewisham'],
    phoneCallAvailability: ['Weekday evenings'],
    newMemberCallDone: false,
    hadInitialOneToOne: false,
    invitedToWhatsApp: false,
    notes:
      'HMO landlord dispute mentioned in the sign-up form. Sensitive subject — let her lead the conversation.',
    dateEnteredInDatabase: '2026-05-07',
  },
  {
    id: 'recSaraPelham',
    name: 'Sara Pelham',
    phoneNumber: '07700 900804',
    contactType: 'Member (paying)',
    tags: ['Hackney', 'Tenants association'],
    phoneCallAvailability: ['Weekday evenings', 'Weekend mornings'],
    newMemberCallDone: true,
    hadInitialOneToOne: true,
    invitedToWhatsApp: true,
    membershipNumber: 3219,
    notes: 'Active in her local tenants association. Strong contact for collective organising.',
    summary: 'Last spoke 5/5/26 — confirmed attendance at the 18 May turnout event.',
    dateEnteredInDatabase: '2023-11-04',
  },
  {
    id: 'recDavidOkafor',
    name: 'David Okafor',
    phoneNumber: '07700 900917',
    contactType: 'Cancelled direct debit',
    tags: ['Hackney'],
    phoneCallAvailability: ['Weekday evenings'],
    newMemberCallDone: true,
    hadInitialOneToOne: true,
    invitedToWhatsApp: true,
    membershipNumber: 2104,
    notes:
      'DD cancelled in April. Worth understanding why — may be financial, may be drift. Approach gently.',
    summary: 'Last engaged at the Feb members meeting. Quiet since.',
    dateEnteredInDatabase: '2022-06-19',
  },
  {
    id: 'recAmiraEl-Sayed',
    name: 'Amira El-Sayed',
    phoneNumber: '07700 901028',
    contactType: 'Member (non-paying)',
    tags: ['Tower Hamlets', 'Solidarity fund'],
    phoneCallAvailability: ['Weekend afternoons'],
    newMemberCallDone: true,
    hadInitialOneToOne: false,
    invitedToWhatsApp: false,
    membershipNumber: 5103,
    notes:
      'Joined on the solidarity fund. Has not yet had a 1:1 — worth booking one in.',
    dateEnteredInDatabase: '2026-02-14',
  },
];
