/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganiseRouteImport } from './routes/organise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'

const OrganiseRoute = OrganiseRouteImport.update({
  id: '/organise',
  path: '/organise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organise': typeof OrganiseRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organise': typeof OrganiseRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organise': typeof OrganiseRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/organise' | '/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/organise' | '/session/$sessionId'
  id: '__root__' | '/' | '/organise' | '/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganiseRoute: typeof OrganiseRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organise': {
      id: '/organise'
      path: '/organise'
      fullPath: '/organise'
      preLoaderRoute: typeof OrganiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganiseRoute: OrganiseRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
